repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python manage.py test
        always_run: true
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: static-typing-check
        name: static-typing-check
        entry: mypy .
        always_run: true
        pass_filenames: false
        language: system
 