# Generated by Django 4.2.1 on 2023-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_rename_points_votes_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='point',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
