# Generated by Django 4.2.1 on 2023-05-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_votes_delete_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='points',
            new_name='point',
        ),
    ]
